# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_choice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='multiple_choice.Question'),
            preserve_default=False,
        ),
    ]
