# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-24 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_choice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer_choice',
        ),
    ]
