# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-30 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_choice', '0002_remove_question_correct_answer_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='incorrect_answer_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='incorrect_answer_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='incorrect_answer_3',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiple_choice.Question'),
        ),
    ]
