# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_choice', '0003_auto_20160409_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer_letter',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
